import AddRoundedIcon from '@mui/icons-material/AddRounded';
import EventOutlinedIcon from '@mui/icons-material/EventOutlined';
import GroupsOutlinedIcon from '@mui/icons-material/GroupsOutlined';
import {
  Alert, Box, Button, Card, Chip, Dialog, DialogActions, DialogContent,
  DialogTitle, MenuItem, Stack, Tab, Table, TableBody, TableCell, TableHead,
  TableRow, Tabs, TextField, Typography,
} from '@mui/material';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useState } from 'react';
import {
  createClub, createEvent, getActivities, updateActivityStatus, updateClub, updateEvent,
  type SchoolClub, type SchoolEvent,
} from '../api/adminOperationsApi';
import { ApiProblem } from '../api/adminAuthApi';
import { useAuth } from '../auth/authState';

function localDateTime(value: Date): string {
  const local = new Date(value.getTime() - value.getTimezoneOffset() * 60_000);
  return local.toISOString().slice(0, 16);
}
const tomorrow = new Date(Date.now() + 86_400_000);
const eventInitial = { category: 'ACADEMIC', title: '', description: '', location: '', startsAt: localDateTime(tomorrow), endsAt: localDateTime(new Date(tomorrow.getTime() + 7_200_000)), audience: 'ALL', audienceGradeLevel: 10, capacity: 100, registrationEnabled: true };
const clubInitial = { category: 'ACADEMIC', name: '', description: '', advisorName: '', meetingSchedule: '', location: '', audience: 'ALL', audienceGradeLevel: 10, capacity: 30, acceptingApplications: true };
const eventCategoryLabels: Record<string, string> = {
  ACADEMIC: 'Học tập', CULTURAL: 'Văn hóa', SPORTS: 'Thể thao', CLUB: 'Câu lạc bộ', CAREER: 'Hướng nghiệp',
};
const clubCategoryLabels: Record<string, string> = {
  ACADEMIC: 'Học thuật', SPORTS: 'Thể thao', ARTS: 'Nghệ thuật', SKILLS: 'Kỹ năng', COMMUNITY: 'Cộng đồng', MEDIA: 'Truyền thông',
};
const registrationStatusLabels: Record<string, string> = {
  REGISTERED: 'Đã đăng ký', CANCELLED: 'Đã hủy', WAITLISTED: 'Danh sách chờ',
};
const membershipStatusLabels: Record<string, string> = {
  PENDING: 'Chờ duyệt', ACTIVE: 'Đang tham gia', REJECTED: 'Đã từ chối', WITHDRAWN: 'Đã rút',
};

export function ActivitiesAdminPage() {
  const { accessToken } = useAuth(); const client = useQueryClient();
  const [tab, setTab] = useState(0); const [dialog, setDialog] = useState<'event'|'club'|null>(null);
  const [eventForm, setEventForm] = useState(eventInitial); const [clubForm, setClubForm] = useState(clubInitial); const [feedback, setFeedback] = useState<string|null>(null);
  const query = useQuery({ queryKey: ['admin-activities'], queryFn: () => getActivities(accessToken!), enabled: Boolean(accessToken) });
  const invalidate = () => client.invalidateQueries({ queryKey: ['admin-activities'] });
  const create = useMutation({ mutationFn: async () => { if (dialog === 'event') await createEvent(accessToken!, { ...eventForm, startsAt: new Date(eventForm.startsAt).toISOString(), endsAt: new Date(eventForm.endsAt).toISOString(), audienceGradeLevel: eventForm.audience === 'GRADE' ? Number(eventForm.audienceGradeLevel) : null, capacity: Number(eventForm.capacity), registrationDeadline: null, cancellationDeadline: null }); else await createClub(accessToken!, { ...clubForm, audienceGradeLevel: clubForm.audience === 'GRADE' ? Number(clubForm.audienceGradeLevel) : null, capacity: Number(clubForm.capacity), applicationDeadline: null }); }, onSuccess: async () => { await invalidate(); setFeedback(dialog === 'event' ? 'Đã tạo sự kiện.' : 'Đã tạo câu lạc bộ.'); setDialog(null); setEventForm(eventInitial); setClubForm(clubInitial); } });
  const toggleEvent = useMutation({ mutationFn: (item: SchoolEvent) => updateEvent(accessToken!, item.id, { ...item, enabled: !item.enabled }), onSuccess: invalidate });
  const toggleClub = useMutation({ mutationFn: (item: SchoolClub) => updateClub(accessToken!, item.id, { ...item, enabled: !item.enabled }), onSuccess: invalidate });
  const status = useMutation({ mutationFn: ({ resource, id, value, version }: { resource: 'event-registrations'|'club-memberships'; id: string; value: string; version: number }) => updateActivityStatus(accessToken!, resource, id, value, version), onSuccess: invalidate });
  const error = create.error ?? toggleEvent.error ?? toggleClub.error ?? status.error;
  return <Stack spacing={2.5}>
    <Box sx={{ display:'flex', justifyContent:'space-between', alignItems:'center', gap:2, flexWrap:'wrap' }}><Box><Typography variant="h4">Sự kiện & CLB</Typography><Typography color="text.secondary">Quản lý hoạt động, đăng ký và thành viên học sinh.</Typography></Box><Stack direction="row" spacing={1}><Button variant="outlined" startIcon={<GroupsOutlinedIcon />} onClick={() => setDialog('club')}>Thêm CLB</Button><Button variant="contained" startIcon={<AddRoundedIcon />} onClick={() => setDialog('event')}>Thêm sự kiện</Button></Stack></Box>
    {feedback && <Alert severity="success" onClose={() => setFeedback(null)}>{feedback}</Alert>}{error && <Alert severity="error">{error instanceof ApiProblem ? error.message : 'Không thể cập nhật hoạt động.'}</Alert>}
    <Card variant="outlined"><Tabs value={tab} onChange={(_, value) => setTab(value)}><Tab label={`Sự kiện (${query.data?.events.length ?? 0})`} /><Tab label={`Câu lạc bộ (${query.data?.clubs.length ?? 0})`} /><Tab label={`Đơn đăng ký (${(query.data?.eventRegistrations.length ?? 0)+(query.data?.clubMemberships.length ?? 0)})`} /></Tabs></Card>
    {tab === 0 && <Box sx={{ display:'grid', gridTemplateColumns:{ xs:'1fr', lg:'repeat(2, 1fr)' }, gap:1.5 }}>{query.data?.events.map((item) => <Card variant="outlined" key={item.id} sx={{ p:2 }}><Stack direction="row" spacing={1.5}><Box sx={{ width:44,height:44,borderRadius:2,bgcolor:'#fff0eb',color:'primary.main',display:'grid',placeItems:'center' }}><EventOutlinedIcon /></Box><Box sx={{ flex:1 }}><Stack direction="row" sx={{ justifyContent: 'space-between', gap: 1 }}><Typography sx={{ fontWeight:750 }}>{item.title}</Typography><Chip size="small" color={item.enabled?'success':'default'} label={item.enabled?'Đang hiển thị':'Đã ẩn'} /></Stack><Typography variant="body2" color="text.secondary">{new Intl.DateTimeFormat('vi-VN',{dateStyle:'medium',timeStyle:'short'}).format(new Date(item.startsAt))} · {item.location}</Typography><Typography variant="caption" color="text.secondary">{item.registeredCount} đăng ký · {eventCategoryLabels[item.category] ?? 'Khác'}</Typography><Box sx={{ mt:1 }}><Button size="small" onClick={() => toggleEvent.mutate(item)}>{item.enabled?'Ẩn sự kiện':'Hiển thị lại'}</Button></Box></Box></Stack></Card>)}</Box>}
    {tab === 1 && <Box sx={{ display:'grid', gridTemplateColumns:{ xs:'1fr', lg:'repeat(2, 1fr)' }, gap:1.5 }}>{query.data?.clubs.map((item) => <Card variant="outlined" key={item.id} sx={{ p:2 }}><Stack direction="row" spacing={1.5}><Box sx={{ width:44,height:44,borderRadius:2,bgcolor:'#edf8f3',color:'success.main',display:'grid',placeItems:'center' }}><GroupsOutlinedIcon /></Box><Box sx={{ flex:1 }}><Stack direction="row" sx={{ justifyContent: 'space-between', gap: 1 }}><Typography sx={{ fontWeight:750 }}>{item.name}</Typography><Chip size="small" color={item.enabled?'success':'default'} label={item.enabled?'Đang hoạt động':'Đã ẩn'} /></Stack><Typography variant="body2" color="text.secondary">{item.meetingSchedule} · {item.location}</Typography><Typography variant="caption" color="text.secondary">{item.activeCount} thành viên · Phụ trách {item.advisorName}</Typography><Box sx={{ mt:1 }}><Button size="small" onClick={() => toggleClub.mutate(item)}>{item.enabled?'Ẩn CLB':'Hiển thị lại'}</Button></Box></Box></Stack></Card>)}</Box>}
    {tab === 2 && <Card variant="outlined"><Table size="small"><TableHead><TableRow><TableCell>Học sinh</TableCell><TableCell>Hoạt động</TableCell><TableCell>Loại</TableCell><TableCell>Trạng thái</TableCell><TableCell align="right">Xử lý</TableCell></TableRow></TableHead><TableBody>
      {query.data?.eventRegistrations.map((item) => <TableRow key={item.id}><TableCell>{item.studentName}<Typography variant="caption" color="text.secondary" sx={{ display: 'block' }}>{item.studentCode}</Typography></TableCell><TableCell>{query.data.events.find((event) => event.id===item.eventId)?.title}</TableCell><TableCell>Sự kiện</TableCell><TableCell><Chip size="small" label={registrationStatusLabels[item.status] ?? 'Không xác định'} /></TableCell><TableCell align="right"><Button size="small" color="error" disabled={item.status==='CANCELLED'} onClick={() => status.mutate({ resource:'event-registrations',id:item.id,value:'CANCELLED',version:item.version })}>Hủy đăng ký</Button></TableCell></TableRow>)}
      {query.data?.clubMemberships.map((item) => <TableRow key={item.id}><TableCell>{item.studentName}<Typography variant="caption" color="text.secondary" sx={{ display: 'block' }}>{item.studentCode}</Typography></TableCell><TableCell>{query.data.clubs.find((club) => club.id===item.clubId)?.name}</TableCell><TableCell>CLB</TableCell><TableCell><Chip size="small" label={membershipStatusLabels[item.status] ?? 'Không xác định'} /></TableCell><TableCell align="right"><Stack direction="row" sx={{ justifyContent: 'flex-end' }}><Button size="small" disabled={item.status==='ACTIVE'} onClick={() => status.mutate({resource:'club-memberships',id:item.id,value:'ACTIVE',version:item.version})}>Duyệt</Button><Button size="small" color="error" disabled={item.status==='REJECTED'} onClick={() => status.mutate({resource:'club-memberships',id:item.id,value:'REJECTED',version:item.version})}>Từ chối</Button></Stack></TableCell></TableRow>)}
    </TableBody></Table></Card>}
    <Dialog open={dialog==='event'} onClose={() => setDialog(null)} fullWidth maxWidth="sm"><DialogTitle>Thêm sự kiện</DialogTitle><DialogContent><Stack spacing={2} sx={{pt:1}}><TextField label="Tên sự kiện" value={eventForm.title} onChange={(e)=>setEventForm({...eventForm,title:e.target.value})}/><TextField label="Mô tả" multiline minRows={3} value={eventForm.description} onChange={(e)=>setEventForm({...eventForm,description:e.target.value})}/><TextField label="Địa điểm" value={eventForm.location} onChange={(e)=>setEventForm({...eventForm,location:e.target.value})}/><TextField select label="Danh mục" value={eventForm.category} onChange={(e)=>setEventForm({...eventForm,category:e.target.value})}>{Object.entries(eventCategoryLabels).map(([value, label])=><MenuItem key={value} value={value}>{label}</MenuItem>)}</TextField><Stack direction="row" spacing={1.5}><TextField fullWidth type="datetime-local" label="Bắt đầu" value={eventForm.startsAt} onChange={(e)=>setEventForm({...eventForm,startsAt:e.target.value})} slotProps={{inputLabel:{shrink:true}}}/><TextField fullWidth type="datetime-local" label="Kết thúc" value={eventForm.endsAt} onChange={(e)=>setEventForm({...eventForm,endsAt:e.target.value})} slotProps={{inputLabel:{shrink:true}}}/></Stack><TextField type="number" label="Sức chứa" value={eventForm.capacity} onChange={(e)=>setEventForm({...eventForm,capacity:Number(e.target.value)})}/></Stack></DialogContent><DialogActions><Button onClick={()=>setDialog(null)}>Hủy</Button><Button variant="contained" disabled={!eventForm.title||!eventForm.location||create.isPending} onClick={()=>create.mutate()}>Tạo sự kiện</Button></DialogActions></Dialog>
    <Dialog open={dialog==='club'} onClose={() => setDialog(null)} fullWidth maxWidth="sm"><DialogTitle>Thêm câu lạc bộ</DialogTitle><DialogContent><Stack spacing={2} sx={{pt:1}}><TextField label="Tên CLB" value={clubForm.name} onChange={(e)=>setClubForm({...clubForm,name:e.target.value})}/><TextField label="Mô tả" multiline minRows={3} value={clubForm.description} onChange={(e)=>setClubForm({...clubForm,description:e.target.value})}/><TextField label="Giáo viên phụ trách" value={clubForm.advisorName} onChange={(e)=>setClubForm({...clubForm,advisorName:e.target.value})}/><TextField label="Lịch sinh hoạt" value={clubForm.meetingSchedule} onChange={(e)=>setClubForm({...clubForm,meetingSchedule:e.target.value})}/><TextField label="Địa điểm" value={clubForm.location} onChange={(e)=>setClubForm({...clubForm,location:e.target.value})}/><TextField select label="Danh mục" value={clubForm.category} onChange={(e)=>setClubForm({...clubForm,category:e.target.value})}>{Object.entries(clubCategoryLabels).map(([value, label])=><MenuItem key={value} value={value}>{label}</MenuItem>)}</TextField><TextField type="number" label="Sức chứa" value={clubForm.capacity} onChange={(e)=>setClubForm({...clubForm,capacity:Number(e.target.value)})}/></Stack></DialogContent><DialogActions><Button onClick={()=>setDialog(null)}>Hủy</Button><Button variant="contained" disabled={!clubForm.name||!clubForm.advisorName||!clubForm.location||create.isPending} onClick={()=>create.mutate()}>Tạo CLB</Button></DialogActions></Dialog>
  </Stack>;
}
